export default {
  icon: 'material',
  placeholder: 'type here to start new note',
  width: '100%',
  height: '100%',
  toolbarConfig: {
    pin: true,
  },
  cache: {
    enable: false,
  },
  preview: {
    delay: 100,
    hljs: {
      lineNumber: true,
    },
  },
  toolbar: [
    'outline',
    '|',
    'headings',
    'bold',
    'italic',
    'strike',
    '|',
    'list',
    'ordered-list',
    'check',
    'line',
    'link',
    'quote',
    'code',
    'inline-code',
    'table',
    '|',
    'insert-after',
    'insert-before',
    'undo',
    'redo',
    '|',
    'edit-mode',
    'code-theme',
    'content-theme',
    'preview',
  ] as string[],
} as const
